Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.network "forwarded_port", guest: 9000, host: 9000

  config.vm.synced_folder "../", "/pysaml2-idp"

  config.vm.provision "docker" do |docker|
    docker.build_image "/pysaml2-idp",
        args: "-t pysaml2-idp"
    docker.run "pysaml2-idp",
        args: "-p 9000:9000 -v /pysaml2-idp/env:/mnt/config -e DATA_DIR=/mnt/config"
  end
end
